sysusers/staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PersonListView.as_view(), name='staff'),
    path('department/<str:dep>/', views.DepartmentView.as_view(), name='department-staff'),
    path('room/<str:room>/', views.RoomView.as_view(), name='room-staff'),
    path('title/<str:title>/', views.TitleView.as_view(), name='title-staff'),
    #path('person/<int:id>/', views.PersonDetailView.as_view(), name='person-detail-staff'),
    path('person/<int:id>/table/', views.PersonDetailViewTable.as_view(), name='person-detail-staff-table'),
    #path('tree/', views.TreeView.as_view(), name='tree'),
    path('tree/<int:id>/', views.PersonTreeView.as_view(), name='person-tree'),
]

sysusers/syspriv/urls.py
from django.urls import path
from . import views
from . import models
from django_filters.views import FilterView
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('update/', views.get_systems, name='update-systems'),
    path('systems/', views.SystemListView.as_view(), name='system-list'),
    path("system/<int:id>/", views.SystemDetailView.as_view(), name='system-detail'),
    path("system-people/<int:id>/", views.SystemPeopleView.as_view(), name='system-people'),
    path('people/', views.PersonListView.as_view(), name='people-list'),
    path("person/<int:id>/",views.PersonDetailView.as_view(), name='person-detail'),
    path('departments/', views.DeaprtmentListView.as_view(), name='department-list'),
    path('department/<int:id>/', views.DeaprtmentDetailView.as_view(), name='department-detail'),
    path('commission-list/', views.CommissionListView.as_view(), name='commission-list'),

    #    path('roles/', views.RolesListView.as_view(), name='roles-list'),
    #    path("getuser/", views.FilterUserView.as_view(), name='user-form'),
    #    path("getsystem/", views.FilterSystemView.as_view(), name='system-form'),
    path('commission/', views.CommissionCreateView.as_view(), name='commission-create'),
    path('commission-filter/', FilterView.as_view(model=models.Commission, filterset_fields=('user_last_name',)), name='commission-filter'),
    path('commission/<int:pk>/', views.CommissionDetailView.as_view(), name='commission-detail'),
    path('test/', views.test_page, name='test-page'),
    path('login/', views.MyLoginView.as_view(),name='login'),
    #path('login/', views.login_redirect,name='login'),
    path('logout/', LogoutView.as_view(next_page='login'),name='logout'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('personpriv/<int:id>/', views.PersonPrivileges.as_view(), name='personpriv'),
    #    path('l/', views.reset, name='reset'),

]

sysusers/sysusers/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("syspriv/", include("syspriv.urls")),
    path('admin/', admin.site.urls, name='admin'),
    path("staff/", include("staff.urls")),
    #path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

sysusers/syspriv/models.py
import logging
from django.db import models
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.template import Context, Template


class System(models.Model):
    db_type_choices = [
        ('fb', 'Firebird'),
        ('MS', 'MS SQL Server'),
        ('PS', "Powershell"),
        ('CS', 'CSV file'),
        ('YA', 'yaml file'),
    ]
    display_name = models.CharField(max_length=60)
    server_name = models.CharField(max_length=60, null=True)
    database = models.CharField(max_length=60, null=True)
    login = models.CharField(max_length=30, null=True)
    password = models.CharField(max_length=30)
    port = models.CharField(max_length=6, null=True)
    db_type = models.CharField(choices=db_type_choices, null=False, max_length=8)
    sql_query_roles = models.TextField()
    sql_query_accounts = models.TextField()
    sql_query_accounts_roles = models.TextField()
    update_time = models.DateTimeField(null=True)
    description = models.TextField(max_length=500, blank=True, default='')

    class Meta:
        ordering = ["display_name",]

    def __str__(self):
        return self.display_name

    def query_system(self):
        from .datasources.base import get_datasource

        ds = get_datasource(self)
        try:
            ds.load_data()
            self.update_time = timezone.now()
            self.save()
            return True
        except Exception as e:
            logging.error(e)
            return False


class Role(models.Model):
    system = models.ForeignKey(System, on_delete=models.CASCADE)
    internal_id = models.CharField(max_length=40)
    name = models.CharField(max_length=60)
    description = models.TextField(max_length=500)
    def __str__(self):
        return self.system.display_name + ': ' + self.name

    class Meta:
        ordering = ["system", "name"]


class AdPerson(models.Model):
    login = models.CharField(max_length=30, default='b.d.') #SamAccountName
    full_name = models.CharField(max_length=40) #Name
    first_name = models.CharField(max_length=30) #GivenName
    last_name = models.CharField(max_length=40) #Surname
    title = models.CharField(max_length=60, null=False, default='b.d.') #Title
    department = models.CharField(max_length=80, default='b.d.') #Department (wydział)
    office = models.CharField(max_length=80, null=False, default='b.d.') #Office (biuro/dzielnica)
    manager = models.CharField(max_length=100, default='b.d.') #Manager
    emailaddress = models.CharField(max_length=50, default='b.d.') #emailaddress
    office_phone = models.CharField(max_length=20, null=True, blank=True) #OfficePhone
    mobile_phone = models.CharField(max_length=20, null=True, blank=True) #MobilePhone
    room_number = models.CharField(max_length=80, null=True, blank=True) #POBox
    thumbnail = models.TextField(null=True) #thumb base64

    def __str__(self):
        return self.full_name

    @classmethod
    def logged_aduser(cls, user):
        try:
            return AdPerson.objects.get(login__iexact=user.username)
        except ObjectDoesNotExist:
            return None

    @classmethod
    def people_from_department(cls, user):
        try:
            user_ad = cls.logged_aduser(user)
            return cls.objects.filter(department=user_ad.department if user_ad else None, office=user_ad.office if user_ad else None)
        except ObjectDoesNotExist:
            return None

    @classmethod
    def people_allowed_for_user(cls, user):
        if user.groups.filter(name='master').exists():
            return cls.objects.all()
        else:
            return cls.people_from_department(user)


    class Meta:
        ordering = ["last_name", "first_name"]

class Account(models.Model):
    system = models.ForeignKey(System, on_delete=models.CASCADE)
    internal_id = models.CharField(max_length=40)
    login = models.CharField(max_length=80)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    roles = models.ManyToManyField(Role, related_name='accounts')
    adperson = models.ForeignKey(AdPerson, null=True, on_delete=models.SET_NULL)
    @property
    def full_name(self):
        return self.last_name + ' ' + self.first_name

    def __str__(self):
        return self.system.display_name + ': ' + self.login

    class Meta:
        ordering = ["last_name", "first_name"]

class Department(models.Model):
    name = models.CharField(max_length=80, default='b.d.')
    office = models.CharField(max_length=80, null=False, default='b.d.')
    systems = models.ManyToManyField(System)

    class Meta:
        ordering = ["office", "name",]

    def __str__(self):
        return self.office + ': ' + self.name


class Commission(models.Model):
    display_id = models.IntegerField(default = 10000)
    manager_first_name = models.CharField(max_length=30)
    manager_last_name = models.CharField(max_length=40)
    person_first_name = models.CharField(max_length=30)
    person_last_name = models.CharField(max_length=40, verbose_name='nazwisko użytkownika')
    request_time = models.DateTimeField(null=False)
    accept_time = models.DateTimeField(null=True, blank=True)
    class Meta:
        ordering = ["display_id",]

    def commision_html(self):
        t = Template('''
    <html>
      <head></head>
      <body>
      Proszę o akceptację wniosku numer {{ object.display_id|stringformat:"05d" }} o zmianę uprawnień dla <b>{{ object.person_first_name}} {{ object.person_last_name}}</b>.<br>
    Wnioskujący: {{object.manager_first_name}} {{object.manager_last_name}}<br> 
    Data utworzenia wniosku: {{object.request_time|date:"Y-m-d H:i"}}<br>
<table style="border: 1px solid black;">
<tr style="text-align:center;"><th>system</th><th>uprawnienie</th><th>status</th></tr>
    {% for d in object.commission_role_set.all %}
    {% cycle '100%' '95%' as brightness silent %}
    <tr style="border: 1px solid black; background-color: white; filter: brightness({{ brightness }});">
    {% if d.status == "-" %}
        <td style="text-decoration: line-through; padding-right: 5px; padding-left: 5px;">{{ d.system_name }}</td>
        <td style="text-decoration: line-through; padding-right: 5px; padding-left: 5px;">{{ d.role_name }}</td>
        <td style="background-color: #FFF0F0; padding-right: 5px; padding-left: 5px;">zabrane</td>
     {% elif d.status == "+" %}
        <td style="font-weight: bold; padding-right: 5px; padding-left: 5px;">{{ d.system_name }}</td>
        <td style="font-weight: bold; padding-right: 5px; padding-left: 5px;">{{ d.role_name }}</td>
        <td style="background-color: #F0FFF0; padding-right: 5px; padding-left: 5px;">dodane</td>
    {% else %}
        <td style="padding-right: 5px; padding-left: 5px;">{{ d.system_name }}</td>
        <td style="padding-right: 5px; padding-left: 5px;">{{ d.role_name }}</td>
        <td style="padding-right: 5px; padding-left: 5px;">b.z.</td>
    {% endif %}
    </tr>
    {% endfor %}
</table>
</body>
</html>
''')
        c = Context({"object": self})
        return t.render(c)

class Commission_role(models.Model):
    ROLE_STATUS = [
        ('+', 'dodane'),
        ('-', 'usunięte'),
        ('=', 'bez zmian')
    ]
    system_name = models.CharField(max_length=60)
    role_name = models.CharField(max_length=60)
    role_internal_id = models.CharField(max_length=40)
    commission = models.ForeignKey(Commission, on_delete=models.CASCADE)
    status = models.CharField(default='=', choices=ROLE_STATUS, max_length=2)

    class Meta:
        ordering = ["system_name","role_name"]


class AdContainer(models.Model):
    # tabela przechowująca stringi z OU do zapytań w AD o użytkowników z wybranych wydziałów
    name = models.CharField(max_length=100)
    string = models.TextField(max_length=500)

class AdUser(models.Model):
    ROLE = [
        ('M', 'master'),
        ('S', 'standard'),
    ]
    login = models.CharField(max_length=30) #SamAccountName
    first_name = models.CharField(max_length=30) #GivenName
    last_name = models.CharField(max_length=40) #Surname
    status = models.CharField(default='S', choices=ROLE, max_length=2)

class Config(models.Model):
    key = models.CharField(max_length=30)
    value = models.CharField(max_length=100)

    def __str__(self):
        return self.key + ': ' + self.value

sysusers/syspriv/forms.py
from django import forms
from .models import System, AdPerson, Account, Role, Department
from django.core.exceptions import ObjectDoesNotExist



class SystemsSelectForm(forms.Form):
    systems = forms.ModelMultipleChoiceField(queryset=System.objects.all().order_by('display_name'),widget=forms.CheckboxSelectMultiple, required=False)

class PersonSelectForm(forms.Form):
    people_who_are_users = Account.objects.values_list('adperson', flat=True).distinct()
    # tabela Adperson ma sporo więcej osób niż użytkownicy systemów
    person = forms.ModelChoiceField(queryset=AdPerson.objects.filter(id__in=people_who_are_users))

class SystemPasswordForm(forms.ModelForm):
    class Meta:
        model = System
        widgets = {
            'password': forms.PasswordInput(),
        }
        fields = ['display_name', 'description', 'server_name', 'database', 'login', 'password', 'port', 'db_type', 'sql_query_roles',
                  'sql_query_accounts', 'sql_query_accounts_roles', 'update_time']



class SystemSelectForm(forms.Form):
    system = forms.ModelChoiceField(queryset=System.objects.all().order_by('display_name'), required=False)


class CommissionCreateForm1(forms.Form):
    person = forms.ModelChoiceField(queryset=AdPerson.objects.all(), required=True, label_suffix=None, label='pracownik')
    auto_id = False
    #def __init__(self, *args, **kwargs):
    #    super(CommissionCreateForm1, self).__init__(*args, **kwargs)
    #    self.fields['person'].queryset = AdPerson.objects.none()


class CommissionCreateForm2(forms.Form):
    roles = forms.ModelMultipleChoiceField(queryset=Role.objects.all(), required=False, widget=forms.CheckboxSelectMultiple(attrs={'use_fieldset': False}))
    auto_id = False

class CommissionCreateForm3(forms.Form):
    _ = forms.CharField(widget=forms.HiddenInput(), required=False)

sysusers/templates/syspriv/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon"/>
    <title>{% block title %}{% endblock %}</title>
    <style>
    .table {
        border: 1px solid;
    }
    .thdr {background-color: antiquewhite; filter: brightness(80%);}
   /*
    .table th {background-color: antiquewhite; filter: brightness(90%);}
    .table-striped>tbody>tr:nth-child(odd)>td,
    .table-striped>tbody>tr:nth-child(odd)>th {
       background-color: antiquewhite;
    }  */
    .nav-item { font-size: 105%; margin-left:5px; margin-right:0px; padding:2px;}

    .alert {
        width:50%;
    }
    @media print
{
    .no-print, .no-print *
    {
        display: none;
    }
}
</style>
</head>
<body>
<div class="container">
{% include 'syspriv/include_menu.html' %}
    {% block content %}{% endblock %}
</div>
</body>
</html>
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

sysusers/templates/syspriv/commission_create0.html
{% extends 'syspriv/base.html' %}
{% block title %}
Zmiana uprawnień
{% endblock %}


{% block content %}
{% for alert in alerts %}
<div class="alert alert-{{alert.type}}" role="alert">
  {{alert.text|safe}}
</div>
{% endfor %}

<p>Krok {{ wizard.steps.step1 }} z {{ wizard.steps.count }}</p>
<form action="" method="post">
  {% csrf_token %}
  {{ wizard.management_form }}
    {{ wizard.form }}
  {% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">&lt;&lt;</button>
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">&lt;</button>
  {% endif %}
  <div style="padding: 10px;">
    <input class="btn btn-primary" type="submit" value="OK"/>
  </div>
</form>
{% endblock %}

sysusers/templates/syspriv/commission_create1.html
{% extends 'syspriv/base.html' %}
{% load syspriv_extras %}
{% block title %}
Zmiana uprawnień
{% endblock %}


{% block content %}
{% for alert in alerts %}
<div class="alert alert-{{alert.type}}" role="alert">
  {{alert.text|safe}}
</div>
{% endfor %}

<p>Krok {{ wizard.steps.step1 }} z {{ wizard.steps.count }}</p>
<h1>{{ person.full_name }}</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ wizard.management_form }}

    {% comment %}
        {{ wizard.form }}
    {% endcomment %}

<div>
    <fieldset>
  <legend>Uprawnienia:</legend>
        <div style="padding: 10px;">
            Skopiuj uprawnienia pracownika
            <select id="id_clone_person">
            {% for p in persons %}
              <option value={{p.pk}}>{{p}}</option>
            {% endfor %}
            </select>
            <button name="load_priv" type="button" type="button" class="btn btn-outline-secondary" value="load_priv" onclick="LoadPrivileges()">kopiuj</button>
        </div>
<script>
    function LoadPrivileges() {
        var chkboxes = document.getElementsByName("1-roles");
        var count = chkboxes.length;
        var selectedPerson = document.getElementById("id_clone_person");
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.open( "GET", "/syspriv/personpriv/" + selectedPerson.value + "/", false );
        xmlHttp.send( null );
        var privs = xmlHttp.responseText.split(",");
        for(var i = 0; i < count; i++){
            if (privs.includes(chkboxes[i].value)) {
                chkboxes[i].checked = true;
            }
            else {
                chkboxes[i].checked = false;
            }
        }
    }
</script>
<div id="id_1-roles">
    <table class="table table-sm">
       {% for role in wizard.form.fields.roles.choices.queryset %}
        {% ifchanged role.system %}
        <tr><td colspan="4" style="background-color: #FEF5E7;"><a data-bs-toggle="collapse" href="#" data-bs-target=".{{role.system|cut:' '}}"><b>{{ role.system.display_name }}</b></a>  &nbsp;<i>{{role.system.description}}</i></td></tr>
        {% endifchanged %}
        {% cycle '100%' '95%' as brightness silent %}
    <tr class="collapse {{ role.system|cut:' ' }}" style="filter: brightness({{ brightness }});">
        <td style="padding-left: 8px;padding-right: 8px;text-align:center"> <label for="id_1-roles_{{ forloop.counter0 }}"><input type="checkbox" name="1-roles" value="{{role.id}}" {% if role in wizard.form.initial.roles %} checked {% endif %}  id="id_1-roles_{{ forloop.counter0 }}"> </label></td>
        <td style="width: 20%"> {{ role.system }}</td>
        <td> {{ role.name }}</td>
        <td> {{ role.description }}</td>
    </tr>

        {% endfor %}
</table>
</div>
    </fieldset>
</div>
    <div style="padding: 10px;">
  {% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit" type="button" class="btn btn-secondary" value="{{ wizard.steps.first }}">&lt;&lt;</button>
  <button name="wizard_goto_step" type="submit" class="btn btn-secondary" value="{{ wizard.steps.prev }}">&lt;</button>
  {% endif %}
  <input type="submit" class="btn btn-primary" value="OK"/>
   </div>
</form>
{% endblock %}

sysusers/templates/syspriv/commission_detail.html
{% extends 'syspriv/base.html' %}

{% block title %}
    Wniosek {{ object.person_first_name}} {{ object.person_last_name}}
{% endblock %}

{% block content %}
    <p class="h1">wniosek numer {{ object.display_id|stringformat:"05d" }}</p>
    <p style="font-size: 150%;">dla {{ object.person_first_name}} {{ object.person_last_name}}<br>
zlecony przez {{ object.manager_first_name}} {{ object.manager_last_name}}<br>
dnia {{object.request_time|date:"Y-m-d H:i"}}</p>
<table style="border: 1px solid black;">
<tr style="text-align:center;"><th>system</th><th>uprawnienie</th><th>status</th></tr>
    {% for d in object.commission_role_set.all %}
    {% cycle '100%' '95%' as brightness silent %}
    <tr style="border: 1px solid black; background-color: white; filter: brightness({{ brightness }});">
    {% if d.status == "-" %}
        <td style="text-decoration: line-through; padding-right: 5px; padding-left: 5px;">{{ d.system_name }}</td>
        <td style="text-decoration: line-through; padding-right: 5px; padding-left: 5px;">{{ d.role_name }}</td>
        <td style="background-color: #FFF0F0; padding-right: 5px; padding-left: 5px;">zabrane</td>
     {% elif d.status == "+" %}
        <td style="font-weight: bold; padding-right: 5px; padding-left: 5px;">{{ d.system_name }}</td>
        <td style="font-weight: bold; padding-right: 5px; padding-left: 5px;">{{ d.role_name }}</td>
        <td style="background-color: #F0FFF0; padding-right: 5px; padding-left: 5px;">dodane</td>
    {% else %}
        <td style="padding-right: 5px; padding-left: 5px;">{{ d.system_name }}</td>
        <td style="padding-right: 5px; padding-left: 5px;">{{ d.role_name }}</td>
        <td style="padding-right: 5px; padding-left: 5px;">b.z.</td>
    {% endif %}
    </tr>
    {% endfor %}
</table>
<div style="padding: 10px;">
    <a type="button" class="btn btn-primary" href="{% url 'commission-list' %}">powrót do listy</a>
</div>

{% endblock %}

sysusers/templates/syspriv/commission_filter.html
{% extends 'syspriv/base.html' %}

{% block title %}
    Lista wniosków
{% endblock %}

{% block content %}
<p class="h1">lista wniosków</p>
   <form method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
<br>
     <table style="min-width:70%;">
        <tr style="background-color: #FEF5E7; border:1px solid;"><th>numer</th><th>pracownik</th><th>zlecił</th><th>data zlecenia</th></tr>
{% for commission in filter.qs %}
    {% cycle '100%' '95%' as brightness silent %}
    <tr style="filter: brightness({{ brightness }}); border:1px solid; background-color:white;">
        <td>{{ commission.display_id|stringformat:"05d" }}</td>
        <td>{{ commission.person_first_name}} {{ commission.person_last_name}}</td>
        <td>{{ commission.manager_first_name}} {{ commission.manager_last_name}}</td>
        <td>{{ commission.request_time|date:"Y-m-d H:i" }}</td>
    </tr>

{% endfor %}
</table>
{% endblock %}

sysusers/templates/syspriv/department_list.html
{% extends 'syspriv/base.html' %}
{% block title %}
    Lista wydziałów
{% endblock %}

{% block content %}
        <h1>Biura/dzielnice/wydziały</h1>
<table class="table table-sm">
        {% for department in departments %}
            {% ifchanged department.office %}
                <tr><td style="background-color:khaki;"><h3>{{ department.office }}</h3></td></tr>
            {% endifchanged %}
            {% cycle '100%' '95%' as brightness silent %}
            <tr>
                <td style="filter: brightness({{ brightness }});">
                    <a href="{% url 'department-detail' id=department.id %}" class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                        {{ department.name }}
                    </a>
                </td>
            </tr>
        {% endfor %}
</table>
{% endblock %}

sysusers/templates/syspriv/home.html
{% extends 'syspriv/base.html' %}
{% block title %}
Home
{% endblock %}

{% block content %}
<H3>
  Zalogowany użytkownik {{ user }}
  {% for group in groups %}
    <span class="badge bg-success"; style="font-size: 70%;">{{group}}</span>
  {% endfor %}
</H3>
{% if ad_user %}
  <H3>{{ad_user.first_name}} {{ad_user.last_name}}<br/></H3>
  <p><i>{{ ad_user.office }}<br/>{{ ad_user.department }}</i></p>


  {% if 'master' in groups %}
  <p>Podgląd uprawnień wszystkich użytkowników wszystkich systemów.</p>
  {% else %}
    {% if systems_allowed|length > 0 %}
      <p>Podgląd uprawnień użytkowników z własnego wydziału oraz wszystkich użytkowników następujących systemów:</p>
      <ul>
        {% for system in systems_allowed %}
        <li>{{system}}</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Podgląd uprawnień użytkowników wyłącznie z własnego wydziału.</p>
    {% endif %}
  {% endif %}
{% endif %}
{% for alert in alerts %}
<div class="alert alert-{{alert.type}}" role="alert">
  {{alert.text}}
</div>
{% endfor %}
{% endblock %}

sysusers/templates/syspriv/include_users_in_systems_2.html
<table style="min-width:80%; border: 1px solid black;">
    <tr style="border: 1px solid black; background-color: Violet; font-size: 150%; font-weight: bold;">
        <td style="padding-left: 5px;"><a href="{% url 'system-detail' id=system.id %} " data-bs-toggle="tooltip" data-bs-title="pokaż wszystkie uprawnienia w systemie" style="text-decoration: none;color:navy;">{{ system.display_name }}</a> <i style="font-size: 70%; font-weight: normal;">{{system.description}}</i></td>
    </tr>
    {% for role, accounts in roles %}
        <tr style="border: 1px solid black; background-color: Thistle;">
            <td style="padding-left: 15px;"><b>{{ role.name }}</b>: <i>{{ role.description }}</i></td>
        </tr>
        {% for account in accounts %}
            <tr>
                <td  style="padding-left: 30px;"><a href="{% url 'person-detail' id=account.adperson.id %}" data-bs-toggle="tooltip" data-bs-title="{{account.login}}" style="text-decoration: none;color:navy;">{{ account.adperson.full_name }}</a></td>
            </tr>
        {% endfor %}
    {% endfor %}
</table>

sysusers/templates/syspriv/list_roles2.html
{% extends 'syspriv/base.html' %}

{% block title %}
    Lista ról
{% endblock %}

{% block content %}
    <p class="h1">Lista ról w systemach</p>
    {% include 'syspriv/include_list_roles2.html' %}
{% endblock %}

sysusers/templates/syspriv/systems_select.html
{% extends 'syspriv/base.html' %}
{% load syspriv_extras %}


{% block title %}
Aktualizacja danych
{% endblock %}

{% block content %}

{% for alert in alerts %}
<div class="alert alert-{{alert.type}}" role="alert">
  {{alert.text|safe}}
</div>
{% endfor %}

<form action="." method="post">
    {% csrf_token %}
    <table class="table table-striped table-sm">
        <tr class="thdr">
            <th></th>
            <th>system</th>
            <th>typ</th>
            <th>serwer</th>
            <th>baza danych</th>
            <th>aktualizacja</th>
        </tr>
        {% for choice in form.fields.systems.choices %}
            <tr>
                <td style="padding-left: 8px;padding-right: 8px;text-align:center">
                  <input type="checkbox" name="systems" value="{{choice.0}}" id="id_systems_{{choice.0}}">
                </td>
                <td>{{ choice.0|get_system_object:"display_name" }}</td>
                <td>{{ choice.0|get_system_object:"db_type" }}</td>
                <td>{{ choice.0|get_system_object:"server_name" }}</td>
                <td>{{ choice.0|get_system_object:"database" }}</td>
                <td>{{ choice.0|get_system_object:"update_time"|date:'Y-m-d H:i' }}</td>
            </tr>
        {% endfor %}
    </table>
    <div style="padding-left: 20px;">
        <input type="submit" class="btn btn-primary" value="aktualizuj dane z wybranych systemów"></input>
        <inline style="padding-left: 20px;">
            <input name="AD" type="submit" class="btn btn-warning" value="aktualizuj użytkowników z AD"></input>
        </inline>
</form>


{% comment %}
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div style="padding: 10px;">
        <input type="submit" class="btn btn-primary" value="aktualizuj dane z wybranych systemów"></input>
    </div>
</form>


<br>


<table class="table table-striped table-sm">
<tr>
    <th>system</th>
    <th>typ</th>
    <th>serwer</th>
    <th>baza danych</th>
    <th>aktualizacja</th>
</tr>
{% for system in systems %}
    <tr>
        <td>{{ system.display_name }}</td>
        <td>{{ system.get_db_type_display }}</td>
        <td>{{ system.server_name }}</td>
        <td>{{ system.database }}</td>
        <td>{{ system.update_time|date:'Y-m-d H:i' }}</td>
    </tr>
{% endfor %}
</table>
{% endcomment %}

{% endblock %}